### ISSUE TITLE
TLS/SSL support

### ISSUE THREAD

**Issue by M0NsTeRRR** [mdlayher/wireguard_exporter#12]
Hello,

Do there any plan to add TLS support like node_exporter to be secured/encrypted ?
https://github.com/prometheus/node_exporter/blob/master/https/README.md

Best regards,

**Comment by mdlayher** [comment]
Sorry, not interested since TLS support in node exporter is also quite new. If this is something you need, I recommend running a reverse proxy or scraping over a WireGuard tunnel.
