### ISSUE TITLE
Same name and Value label

### ISSUE THREAD

**Issue by markthehipster** [mdlayher/wireguard_exporter#7]
Hey mdlayher, 

I have just experienced an issue where I get this: 

```
An error has occurred while serving metrics:

3 error(s) occurred:
* collected metric "wireguard_peer_receive_bytes_total" { label:<name:"public_key" value:"REDACTED" > counter:<value:526256 > } was collected before with the same name and label values
* collected metric "wireguard_peer_transmit_bytes_total" { label:<name:"public_key" value:"REDACTED" > counter:<value:51184 > } was collected before with the same name and label values
* collected metric "wireguard_peer_last_handshake_seconds" { label:<name:"public_key" value:"REDACTED" > gauge:<value:1.588091946e+09 > } was collected before with the same name and label values
```
Any idea on what this could be and how would I go about fixing it 👍 ? 

Thank you! 
Mark

**Comment by mdlayher** [comment]
Do you have multiple WireGuard interfaces with the same peer configured on multiple interfaces? Can you share the output of `wg show`?

**Comment by markthehipster** [comment]
We do have that, we use 6 interfaces as of the moment.
Would it be possible to exporting measurements for just one config?  (that case we could set up multiple exporters as needed / interface.)
Unfortunately I cannot share it due to company policy.

**Comment by mdlayher** [comment]
I don't understand why you would want to have one peer associated with multiple interfaces on the same machine. Can you explain? I would rather not write special case logic.

**Comment by mdlayher** [comment]
I discussed this with a couple of folks and they mentioned an interesting use case: perhaps you'd like to set up one peer on different devices with different IP stacks, for example IPv4 only, IPv6 only, or dual stack configuration. This could be useful for testing in various scenarios. I'll have a change committed today to fix this.

**Comment by mdlayher** [comment]
Fixed in https://github.com/mdlayher/wireguard_exporter/commit/deab2b8a5933fb9a3ae2a1bbf9ad509ebfe13a96.

**Comment by cbluth** [comment]
@mdlayher 

thanks for this, i will be trying this out too.
i use multiple separate wireguard networks in concert;  some hosts being part of several networks for routing to other networks.
so many of my hosts have multiple wireguard interfaces.
